"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.EXAMPLE_DATA_DRAGON_FESTIVAL = exports.EXAMPLE_DATA_CHILDREN_FESTIVAL = exports.EXAMPLE_DATA_COLLEGE_ENTRANCE_EXAMINATION = exports.LOCALSTORAGE_PREVIEW_CHACHE = exports.LOCALSTORAGE_PREVIEW_NAMESPACE = exports.ANIMATE_REPEAT_NORMAL = exports.ANIMATE_REPEAT_INFINITE = exports.COMPONENT_STYLE_ROTATE = exports.COMPONENT_STYLE_LEFT = exports.COMPONENT_STYLE_TOP = exports.COMPONENT_STYLE_HEIGHT = exports.COMPONENT_STYLE_WIDHT = exports.ITEM_TYPE_GROUP = exports.ITEM_TYPE_SINGLE = exports.COMPONENT_TYPE_ART_BORDER = exports.COMPONENT_TYPE_ART_SOLID = exports.COMPONENT_TYPE_ART_SHADOW = exports.COMPONENT_TYPE_TEXT_TYPED = exports.COMPONENT_TYPE_VIDEO = exports.COMPONENT_TYPE_SHAPE = exports.COMPONENT_TYPE_MAP = exports.COMPONENT_TYPE_ART_INPUT = exports.COMPONENT_TYPE_INPUT = exports.COMPONENT_TYPE_BUTTON = exports.COMPONENT_TYPE_QQ_VIDEO = exports.COMPONENT_TYPE_PICTURE = exports.COMPONENT_TYPE_TEXT = exports.ACTION_ACTVIE_ALIGN_BOTTOM = exports.ACTION_ACTVIE_ALIGN_TOP = exports.ACTION_ACTVIE_ALIGN_RIGHT = exports.ACTION_ACTVIE_ALIGN_LEFT = exports.ACTION_CHANGE_ACTIVE_ITEM_ATTRS = exports.ACTION_MULTI_ACTIVE_ALIGN = exports.ACTION_MULTI_ALIGN_CENTER_HORIZONTAL = exports.ACTION_MULTI_ALIGN_CENTER_VERTICAL = exports.ACTION_MULTI_ALIGN_CENTER = exports.ACTION_MULTI_ALIGN_BOTTOM = exports.ACTION_MULTI_ALIGN_TOP = exports.ACTION_MULTI_ALIGN_RIGHT = exports.ACTION_MULTI_ALIGN_LEFT = exports.ACTION_ANIMATES_EMPTY = exports.ACTION_ANIMATES_HOVER = exports.ACTION_ANIMATES_PREVIEW_ONE = exports.ACTION_ANIMATES_PREVIEW = exports.ACTION_ANIMATES_CHANGE = exports.ACTION_ANIMATES_REMOVE = exports.ACTION_ANIMATES_ADD = exports.ACTION_PAGE_MOVE_DOWN = exports.ACTION_PAGE_MOVE_UP = exports.ACTION_RESORT_GROUP_ITEM = exports.ACTION_CHANGE_ITEM_NAME = exports.ACTION_CHANGE_ITEM_BORDER = exports.ACTION_INIT_HISTORY_STORE = exports.ACTION_ADD_PAGE_ITEM_WITH_SIZE = exports.ACTION_ADD_PAGE_ITEM_WITH_ATTRS = exports.ACTION_DELETE_PAGE = exports.ACTION_COPY_ITEM = exports.ACTION_COPY_PAGE = exports.CHANGE_ANIMATION = exports.STORE_GROUP_SPLIT = exports.STORE_GROUP_ACTIVE_EDIT_KEYS = exports.STORE_INIT_TO_EDIT = exports.STORE_RESET_TO_EDIT = exports.STORE_CHANGE_BACK_MUSIC_URL = exports.CHANGE_ALL_PAGE_BACKGROUND = exports.PAGE_ITEM_RESORT = exports.SAVE_MOVE_START_RECT = exports.CHANGE_ITEM_ROTATE = exports.REMOVE_ITEM = exports.ADD_PAGE_ITEM = exports.CHANGE_ACTIVE_PAGE = exports.STORE_ADD_PAGE = exports.CHANGE_ITEM_BASE_STYLE = exports.CHANGE_ITEM_ATTR = exports.ADD_ITEM_ATTRS = exports.ADD_ACTIVE_EDIT_KEY = exports.CHANGE_ACTIVE_EDIT_KEY = exports.RESET_CONTENT_HEIGHT = exports.CREATE_ITEM_STORE = exports.MOVE_CHANGE = exports.MOVE_END = exports.MOVE_START = exports.ALL_ITEM = exports.POINT_ROTATE = exports.POINT_RIGHT_BOTTOM = exports.POINT_LEFT_BOTTOM = exports.POINT_RIGHT_TOP = exports.POINT_LEFT_TOP = exports.POINT_BOTTOM_CENTER = exports.POINT_TOP_CENTER = exports.POINT_RIGHT_CENTER = exports.POINT_LEFT_CENTER = exports.POINT_BOTTOM = exports.POINT_TOP = exports.POINT_RIGHT = exports.POINT_LEFT = exports.QUADRANT_FOUR = exports.QUADRANT_THREE = exports.QUADRANT_SECOND = exports.QUADRANT_FIRST = void 0;
exports.TYPE_PREVIEW_ANIMATE_HOVER = exports.TYPE_PREVIEW_ANIMATE_CURRENT = exports.TYPE_PREVIEW_ANIMATE_ALL = exports.STYLE_KEY_TYPE_ALL = exports.STYLE_VALUE_TYPE_NUMBER = exports.STYLE_RENDER_TYPE_PICTURE = exports.STYLE_RENDER_TYPE_TWO_INPUT = exports.STYLE_RENDER_TYPE_COLLAPSE = exports.STYLE_RENDER_TYPE_CONTENT_EDIT_DIV = exports.STYLE_RENDER_TYPE_HIDDEN = exports.STYLE_RENDER_TYPE_CUSTOM = exports.STYLE_RENDER_TYPE_SLIDER_INPUT = exports.STYLE_RENDER_TYPE_TEXTAREA = exports.STYLE_RENDER_TYPE_INPUT = exports.STYLE_RENDER_TYPE_SELECT = exports.STYLE_RENDER_TYPE_COLOR = exports.EXAMPLE_DATA_PREVIEW = exports.EXAMPLE_DATA_NEW_YEAR_2020 = exports.EXAMPLE_DATA_THINKSGIVING = exports.EXAMPLE_DATA_DOUBLE_TWENTY = exports.EXAMPLE_DATA_DOUBLE_ELEVEN = exports.EXAMPLE_DATA_1024 = void 0;
// 象限标识
// 第一
var QUADRANT_FIRST = 1; // 第二

exports.QUADRANT_FIRST = QUADRANT_FIRST;
var QUADRANT_SECOND = 2; // 第三

exports.QUADRANT_SECOND = QUADRANT_SECOND;
var QUADRANT_THREE = 3; // 第四

exports.QUADRANT_THREE = QUADRANT_THREE;
var QUADRANT_FOUR = 4; // 标识控制点

exports.QUADRANT_FOUR = QUADRANT_FOUR;
var POINT_LEFT = 'l';
exports.POINT_LEFT = POINT_LEFT;
var POINT_RIGHT = 'r';
exports.POINT_RIGHT = POINT_RIGHT;
var POINT_TOP = 't';
exports.POINT_TOP = POINT_TOP;
var POINT_BOTTOM = 'b';
exports.POINT_BOTTOM = POINT_BOTTOM;
var POINT_LEFT_CENTER = 'lc';
exports.POINT_LEFT_CENTER = POINT_LEFT_CENTER;
var POINT_RIGHT_CENTER = 'rc';
exports.POINT_RIGHT_CENTER = POINT_RIGHT_CENTER;
var POINT_TOP_CENTER = 'tc';
exports.POINT_TOP_CENTER = POINT_TOP_CENTER;
var POINT_BOTTOM_CENTER = 'bc';
exports.POINT_BOTTOM_CENTER = POINT_BOTTOM_CENTER;
var POINT_LEFT_TOP = 'lt';
exports.POINT_LEFT_TOP = POINT_LEFT_TOP;
var POINT_RIGHT_TOP = 'rt';
exports.POINT_RIGHT_TOP = POINT_RIGHT_TOP;
var POINT_LEFT_BOTTOM = 'lb';
exports.POINT_LEFT_BOTTOM = POINT_LEFT_BOTTOM;
var POINT_RIGHT_BOTTOM = 'rb';
exports.POINT_RIGHT_BOTTOM = POINT_RIGHT_BOTTOM;
var POINT_ROTATE = 'rotate'; // action type
// 移动整个框

exports.POINT_ROTATE = POINT_ROTATE;
var ALL_ITEM = 'ALL_ITEM'; // 开始移动

exports.ALL_ITEM = ALL_ITEM;
var MOVE_START = 'MOVE_START'; // 移动结束

exports.MOVE_START = MOVE_START;
var MOVE_END = 'MOVE_END'; // 移动取消

exports.MOVE_END = MOVE_END;
var MOVE_CHANGE = 'MOVE_CHANGE'; // 创建编辑框初始配置

exports.MOVE_CHANGE = MOVE_CHANGE;
var CREATE_ITEM_STORE = 'CREATE_ITEM_STORE'; // 重置内容高度

exports.CREATE_ITEM_STORE = CREATE_ITEM_STORE;
var RESET_CONTENT_HEIGHT = 'RESET_CONTENT_HEIGHT'; // 改变当前激活的编辑框标识

exports.RESET_CONTENT_HEIGHT = RESET_CONTENT_HEIGHT;
var CHANGE_ACTIVE_EDIT_KEY = 'CHANGE_ACTIVE_EDIT_KEY'; // 添加当前激活的编辑框标识

exports.CHANGE_ACTIVE_EDIT_KEY = CHANGE_ACTIVE_EDIT_KEY;
var ADD_ACTIVE_EDIT_KEY = 'ADD_ACTIVE_EDIT_KEY'; // 添加额外属性

exports.ADD_ACTIVE_EDIT_KEY = ADD_ACTIVE_EDIT_KEY;
var ADD_ITEM_ATTRS = 'ADD_ITEM_ATTRS'; // 改变额外属性

exports.ADD_ITEM_ATTRS = ADD_ITEM_ATTRS;
var CHANGE_ITEM_ATTR = 'CHANGE_ITEM_ATTR'; // 改变基础几何属性

exports.CHANGE_ITEM_ATTR = CHANGE_ITEM_ATTR;
var CHANGE_ITEM_BASE_STYLE = 'CHANGE_ITEM_BASE_STYLE'; // 添加页面

exports.CHANGE_ITEM_BASE_STYLE = CHANGE_ITEM_BASE_STYLE;
var STORE_ADD_PAGE = 'STORE_ADD_PAGE'; // 切换激活页面

exports.STORE_ADD_PAGE = STORE_ADD_PAGE;
var CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE'; // 添加页面元素

exports.CHANGE_ACTIVE_PAGE = CHANGE_ACTIVE_PAGE;
var ADD_PAGE_ITEM = 'ADD_PAGE_ITEM'; // 移除页面元素

exports.ADD_PAGE_ITEM = ADD_PAGE_ITEM;
var REMOVE_ITEM = 'REMOVE_ITEM'; // 修改元素旋转角度

exports.REMOVE_ITEM = REMOVE_ITEM;
var CHANGE_ITEM_ROTATE = 'CHANGE_ITEM_ROTATE'; // 修改元素旋转角度

exports.CHANGE_ITEM_ROTATE = CHANGE_ITEM_ROTATE;
var SAVE_MOVE_START_RECT = 'SAVE_MOVE_START_RECT'; // 页面元素重新排序

exports.SAVE_MOVE_START_RECT = SAVE_MOVE_START_RECT;
var PAGE_ITEM_RESORT = 'PAGE_ITEM_RESORT'; // 修改背景图片

exports.PAGE_ITEM_RESORT = PAGE_ITEM_RESORT;
var CHANGE_ALL_PAGE_BACKGROUND = 'CHANGE_ALL_PAGE_BACKGROUND'; // 修改背景音效

exports.CHANGE_ALL_PAGE_BACKGROUND = CHANGE_ALL_PAGE_BACKGROUND;
var STORE_CHANGE_BACK_MUSIC_URL = 'STORE_CHANGE_BACK_MUSIC_URL'; // 重置store以供编辑

exports.STORE_CHANGE_BACK_MUSIC_URL = STORE_CHANGE_BACK_MUSIC_URL;
var STORE_RESET_TO_EDIT = 'STORE_RESET_TO_EDIT'; // 初始化store以供编辑，完全依赖外部数据重置

exports.STORE_RESET_TO_EDIT = STORE_RESET_TO_EDIT;
var STORE_INIT_TO_EDIT = 'STORE_INIT_TO_EDIT'; // 分组编辑状态下元素

exports.STORE_INIT_TO_EDIT = STORE_INIT_TO_EDIT;
var STORE_GROUP_ACTIVE_EDIT_KEYS = 'STORE_GROUP_ACTIVE_EDIT_KEYS'; // 拆分组合元素

exports.STORE_GROUP_ACTIVE_EDIT_KEYS = STORE_GROUP_ACTIVE_EDIT_KEYS;
var STORE_GROUP_SPLIT = 'STORE_GROUP_SPLIT'; // 修改动画属性

exports.STORE_GROUP_SPLIT = STORE_GROUP_SPLIT;
var CHANGE_ANIMATION = 'CHANGE_ANIMATION'; // 拷贝页面

exports.CHANGE_ANIMATION = CHANGE_ANIMATION;
var ACTION_COPY_PAGE = 'ACTION_COPY_PAGE'; // 拷贝单个元素

exports.ACTION_COPY_PAGE = ACTION_COPY_PAGE;
var ACTION_COPY_ITEM = 'ACTION_COPY_ITEM'; // 删除单个页面

exports.ACTION_COPY_ITEM = ACTION_COPY_ITEM;
var ACTION_DELETE_PAGE = 'ACTION_DELETE_PAGE'; // 新增元素，附带私有属性

exports.ACTION_DELETE_PAGE = ACTION_DELETE_PAGE;
var ACTION_ADD_PAGE_ITEM_WITH_ATTRS = 'ACTION_ADD_PAGE_ITEM_WITH_ATTRS'; // 新增元素，附带尺寸

exports.ACTION_ADD_PAGE_ITEM_WITH_ATTRS = ACTION_ADD_PAGE_ITEM_WITH_ATTRS;
var ACTION_ADD_PAGE_ITEM_WITH_SIZE = 'ACTION_ADD_PAGE_ITEM_WITH_SIZE'; // 初始化store，在撤销重做里使用

exports.ACTION_ADD_PAGE_ITEM_WITH_SIZE = ACTION_ADD_PAGE_ITEM_WITH_SIZE;
var ACTION_INIT_HISTORY_STORE = 'ACTION_INIT_HISTORY_STORE'; // 修改元素边框尺寸

exports.ACTION_INIT_HISTORY_STORE = ACTION_INIT_HISTORY_STORE;
var ACTION_CHANGE_ITEM_BORDER = 'ACTION_CHANGE_ITEM_BORDER'; // 修改元素名称

exports.ACTION_CHANGE_ITEM_BORDER = ACTION_CHANGE_ITEM_BORDER;
var ACTION_CHANGE_ITEM_NAME = 'ACTION_CHANGE_ITEM_NAME'; // 重排组内元素次序

exports.ACTION_CHANGE_ITEM_NAME = ACTION_CHANGE_ITEM_NAME;
var ACTION_RESORT_GROUP_ITEM = 'ACTION_RESORT_GROUP_ITEM'; // 将当前页面上移

exports.ACTION_RESORT_GROUP_ITEM = ACTION_RESORT_GROUP_ITEM;
var ACTION_PAGE_MOVE_UP = 'ACTION_PAGE_MOVE_UP'; // 将当前页面下移

exports.ACTION_PAGE_MOVE_UP = ACTION_PAGE_MOVE_UP;
var ACTION_PAGE_MOVE_DOWN = 'ACTION_PAGE_MOVE_DOWN'; // 添加一个动画

exports.ACTION_PAGE_MOVE_DOWN = ACTION_PAGE_MOVE_DOWN;
var ACTION_ANIMATES_ADD = 'ACTION_ANIMATES_ADD'; // 删除一个动画

exports.ACTION_ANIMATES_ADD = ACTION_ANIMATES_ADD;
var ACTION_ANIMATES_REMOVE = 'ACTION_ANIMATES_REMOVE'; // 修改一个动画

exports.ACTION_ANIMATES_REMOVE = ACTION_ANIMATES_REMOVE;
var ACTION_ANIMATES_CHANGE = 'ACTION_ANIMATES_CHANGE'; // 预览整个动画

exports.ACTION_ANIMATES_CHANGE = ACTION_ANIMATES_CHANGE;
var ACTION_ANIMATES_PREVIEW = 'ACTION_ANIMATES_PREVIEW'; // 预览一个动画

exports.ACTION_ANIMATES_PREVIEW = ACTION_ANIMATES_PREVIEW;
var ACTION_ANIMATES_PREVIEW_ONE = 'ACTION_ANIMATES_PREVIEW_ONE'; // 鼠标移动到动画上预览

exports.ACTION_ANIMATES_PREVIEW_ONE = ACTION_ANIMATES_PREVIEW_ONE;
var ACTION_ANIMATES_HOVER = 'ACTION_ANIMATES_HOVER'; // 置空动画预览

exports.ACTION_ANIMATES_HOVER = ACTION_ANIMATES_HOVER;
var ACTION_ANIMATES_EMPTY = 'ACTION_ANIMATES_EMPTY'; // 多个激活态元素对齐方式-左对齐

exports.ACTION_ANIMATES_EMPTY = ACTION_ANIMATES_EMPTY;
var ACTION_MULTI_ALIGN_LEFT = 'ACTION_MULTI_ALIGN_LEFT'; // 多个激活态元素对齐方式-右对齐

exports.ACTION_MULTI_ALIGN_LEFT = ACTION_MULTI_ALIGN_LEFT;
var ACTION_MULTI_ALIGN_RIGHT = 'ACTION_MULTI_ALIGN_RIGHT'; // 多个激活态元素对齐方式-上对齐

exports.ACTION_MULTI_ALIGN_RIGHT = ACTION_MULTI_ALIGN_RIGHT;
var ACTION_MULTI_ALIGN_TOP = 'ACTION_MULTI_ALIGN_TOP'; // 多个激活态元素对齐方式-下对齐

exports.ACTION_MULTI_ALIGN_TOP = ACTION_MULTI_ALIGN_TOP;
var ACTION_MULTI_ALIGN_BOTTOM = 'ACTION_MULTI_ALIGN_BOTTOM'; // 多个激活态元素对齐方式-下对齐

exports.ACTION_MULTI_ALIGN_BOTTOM = ACTION_MULTI_ALIGN_BOTTOM;
var ACTION_MULTI_ALIGN_CENTER = 'ACTION_MULTI_ALIGN_CENTER'; // 多个激活态元素对齐方式-下对齐

exports.ACTION_MULTI_ALIGN_CENTER = ACTION_MULTI_ALIGN_CENTER;
var ACTION_MULTI_ALIGN_CENTER_VERTICAL = 'ACTION_MULTI_ALIGN_CENTER_VERTICAL'; // 多个激活态元素对齐方式-下对齐

exports.ACTION_MULTI_ALIGN_CENTER_VERTICAL = ACTION_MULTI_ALIGN_CENTER_VERTICAL;
var ACTION_MULTI_ALIGN_CENTER_HORIZONTAL = 'ACTION_MULTI_ALIGN_CENTER_HORIZONTAL'; // 修改多个激活态元素对齐方式

exports.ACTION_MULTI_ALIGN_CENTER_HORIZONTAL = ACTION_MULTI_ALIGN_CENTER_HORIZONTAL;
var ACTION_MULTI_ACTIVE_ALIGN = 'ACTION_MULTI_ACTIVE_ALIGN'; // 修改激活态元素属性

exports.ACTION_MULTI_ACTIVE_ALIGN = ACTION_MULTI_ACTIVE_ALIGN;
var ACTION_CHANGE_ACTIVE_ITEM_ATTRS = 'ACTION_CHANGE_ACTIVE_ITEM_ATTRS'; // 单个激活态元素对齐方式-左对齐

exports.ACTION_CHANGE_ACTIVE_ITEM_ATTRS = ACTION_CHANGE_ACTIVE_ITEM_ATTRS;
var ACTION_ACTVIE_ALIGN_LEFT = 'ACTION_ACTVIE_ALIGN_LEFT'; // 单个激活态元素对齐方式-右对齐

exports.ACTION_ACTVIE_ALIGN_LEFT = ACTION_ACTVIE_ALIGN_LEFT;
var ACTION_ACTVIE_ALIGN_RIGHT = 'ACTION_ACTVIE_ALIGN_RIGHT'; // 单个激活态元素对齐方式-上对齐

exports.ACTION_ACTVIE_ALIGN_RIGHT = ACTION_ACTVIE_ALIGN_RIGHT;
var ACTION_ACTVIE_ALIGN_TOP = 'ACTION_ACTVIE_ALIGN_TOP'; // 单个激活态元素对齐方式-下对齐

exports.ACTION_ACTVIE_ALIGN_TOP = ACTION_ACTVIE_ALIGN_TOP;
var ACTION_ACTVIE_ALIGN_BOTTOM = 'ACTION_ACTVIE_ALIGN_BOTTOM'; // 组件类型
// 文本

exports.ACTION_ACTVIE_ALIGN_BOTTOM = ACTION_ACTVIE_ALIGN_BOTTOM;
var COMPONENT_TYPE_TEXT = 'COMPONENT_TYPE_TEXT'; // 图片

exports.COMPONENT_TYPE_TEXT = COMPONENT_TYPE_TEXT;
var COMPONENT_TYPE_PICTURE = 'COMPONENT_TYPE_PICTURE'; // qq视频通话界面

exports.COMPONENT_TYPE_PICTURE = COMPONENT_TYPE_PICTURE;
var COMPONENT_TYPE_QQ_VIDEO = 'COMPONENT_TYPE_QQ_VIDEO'; // 按钮

exports.COMPONENT_TYPE_QQ_VIDEO = COMPONENT_TYPE_QQ_VIDEO;
var COMPONENT_TYPE_BUTTON = 'COMPONENT_TYPE_BUTTON'; // 输入框

exports.COMPONENT_TYPE_BUTTON = COMPONENT_TYPE_BUTTON;
var COMPONENT_TYPE_INPUT = 'COMPONENT_TYPE_INPUT'; // 艺术字

exports.COMPONENT_TYPE_INPUT = COMPONENT_TYPE_INPUT;
var COMPONENT_TYPE_ART_INPUT = 'COMPONENT_TYPE_ART_INPUT'; // 地图

exports.COMPONENT_TYPE_ART_INPUT = COMPONENT_TYPE_ART_INPUT;
var COMPONENT_TYPE_MAP = 'COMPONENT_TYPE_MAP'; // 形状

exports.COMPONENT_TYPE_MAP = COMPONENT_TYPE_MAP;
var COMPONENT_TYPE_SHAPE = 'COMPONENT_TYPE_SHAPE'; // 视频

exports.COMPONENT_TYPE_SHAPE = COMPONENT_TYPE_SHAPE;
var COMPONENT_TYPE_VIDEO = 'COMPONENT_TYPE_VIDEO'; // 文字打字机

exports.COMPONENT_TYPE_VIDEO = COMPONENT_TYPE_VIDEO;
var COMPONENT_TYPE_TEXT_TYPED = 'COMPONENT_TYPE_TEXT_TYPED'; // 艺术字 - 阴影

exports.COMPONENT_TYPE_TEXT_TYPED = COMPONENT_TYPE_TEXT_TYPED;
var COMPONENT_TYPE_ART_SHADOW = 'COMPONENT_TYPE_ART_SHADOW'; // 艺术字 - 立体

exports.COMPONENT_TYPE_ART_SHADOW = COMPONENT_TYPE_ART_SHADOW;
var COMPONENT_TYPE_ART_SOLID = 'COMPONENT_TYPE_ART_SOLID'; // 艺术字 - 描边

exports.COMPONENT_TYPE_ART_SOLID = COMPONENT_TYPE_ART_SOLID;
var COMPONENT_TYPE_ART_BORDER = 'COMPONENT_TYPE_ART_BORDER';
/* 节点类型 */
// 单一节点

exports.COMPONENT_TYPE_ART_BORDER = COMPONENT_TYPE_ART_BORDER;
var ITEM_TYPE_SINGLE = 'ITEM_TYPE_SINGLE'; // 组节点

exports.ITEM_TYPE_SINGLE = ITEM_TYPE_SINGLE;
var ITEM_TYPE_GROUP = 'ITEM_TYPE_GROUP'; // 组件设置

exports.ITEM_TYPE_GROUP = ITEM_TYPE_GROUP;
var COMPONENT_STYLE_WIDHT = 'width';
exports.COMPONENT_STYLE_WIDHT = COMPONENT_STYLE_WIDHT;
var COMPONENT_STYLE_HEIGHT = 'height';
exports.COMPONENT_STYLE_HEIGHT = COMPONENT_STYLE_HEIGHT;
var COMPONENT_STYLE_TOP = 'top';
exports.COMPONENT_STYLE_TOP = COMPONENT_STYLE_TOP;
var COMPONENT_STYLE_LEFT = 'left';
exports.COMPONENT_STYLE_LEFT = COMPONENT_STYLE_LEFT;
var COMPONENT_STYLE_ROTATE = 'rotate';
/* 动画相关 */

exports.COMPONENT_STYLE_ROTATE = COMPONENT_STYLE_ROTATE;
var ANIMATE_REPEAT_INFINITE = 'infinite';
exports.ANIMATE_REPEAT_INFINITE = ANIMATE_REPEAT_INFINITE;
var ANIMATE_REPEAT_NORMAL = 1;
/* 本地缓存相关 */
// 命名空间

exports.ANIMATE_REPEAT_NORMAL = ANIMATE_REPEAT_NORMAL;
var LOCALSTORAGE_PREVIEW_NAMESPACE = 'lz-h5-edit'; // 预览数据标识

exports.LOCALSTORAGE_PREVIEW_NAMESPACE = LOCALSTORAGE_PREVIEW_NAMESPACE;
var LOCALSTORAGE_PREVIEW_CHACHE = 'cache';
/* 示例数据路由标识 */
// 高考加油展示

exports.LOCALSTORAGE_PREVIEW_CHACHE = LOCALSTORAGE_PREVIEW_CHACHE;
var EXAMPLE_DATA_COLLEGE_ENTRANCE_EXAMINATION = 'college'; // 儿童节展示

exports.EXAMPLE_DATA_COLLEGE_ENTRANCE_EXAMINATION = EXAMPLE_DATA_COLLEGE_ENTRANCE_EXAMINATION;
var EXAMPLE_DATA_CHILDREN_FESTIVAL = 'children'; // 端午节展示

exports.EXAMPLE_DATA_CHILDREN_FESTIVAL = EXAMPLE_DATA_CHILDREN_FESTIVAL;
var EXAMPLE_DATA_DRAGON_FESTIVAL = 'dragon'; // 1024程序员节展示

exports.EXAMPLE_DATA_DRAGON_FESTIVAL = EXAMPLE_DATA_DRAGON_FESTIVAL;
var EXAMPLE_DATA_1024 = 'IT1024'; // 双十一展示

exports.EXAMPLE_DATA_1024 = EXAMPLE_DATA_1024;
var EXAMPLE_DATA_DOUBLE_ELEVEN = 'double11'; // 双十二展示

exports.EXAMPLE_DATA_DOUBLE_ELEVEN = EXAMPLE_DATA_DOUBLE_ELEVEN;
var EXAMPLE_DATA_DOUBLE_TWENTY = 'double12'; // 感恩节展示

exports.EXAMPLE_DATA_DOUBLE_TWENTY = EXAMPLE_DATA_DOUBLE_TWENTY;
var EXAMPLE_DATA_THINKSGIVING = 'thinksgiving'; // 2020元旦展示

exports.EXAMPLE_DATA_THINKSGIVING = EXAMPLE_DATA_THINKSGIVING;
var EXAMPLE_DATA_NEW_YEAR_2020 = 'newyear2020'; // 使用缓存数据标识

exports.EXAMPLE_DATA_NEW_YEAR_2020 = EXAMPLE_DATA_NEW_YEAR_2020;
var EXAMPLE_DATA_PREVIEW = 'cache';
/* 样式渲染组件表示 */
// 颜色

exports.EXAMPLE_DATA_PREVIEW = EXAMPLE_DATA_PREVIEW;
var STYLE_RENDER_TYPE_COLOR = 'STYLE_RENDER_TYPE_COLOR'; // 选择框

exports.STYLE_RENDER_TYPE_COLOR = STYLE_RENDER_TYPE_COLOR;
var STYLE_RENDER_TYPE_SELECT = 'STYLE_RENDER_TYPE_SELECT'; // 输入框

exports.STYLE_RENDER_TYPE_SELECT = STYLE_RENDER_TYPE_SELECT;
var STYLE_RENDER_TYPE_INPUT = 'STYLE_RENDER_TYPE_INPUT'; // 多行输入框

exports.STYLE_RENDER_TYPE_INPUT = STYLE_RENDER_TYPE_INPUT;
var STYLE_RENDER_TYPE_TEXTAREA = 'STYLE_RENDER_TYPE_TEXTAREA'; // 带滑动条的输入框

exports.STYLE_RENDER_TYPE_TEXTAREA = STYLE_RENDER_TYPE_TEXTAREA;
var STYLE_RENDER_TYPE_SLIDER_INPUT = 'STYLE_RENDER_TYPE_SLIDER_INPUT'; // 自定义

exports.STYLE_RENDER_TYPE_SLIDER_INPUT = STYLE_RENDER_TYPE_SLIDER_INPUT;
var STYLE_RENDER_TYPE_CUSTOM = 'STYLE_RENDER_TYPE_CUSTOM'; // 不需要显示

exports.STYLE_RENDER_TYPE_CUSTOM = STYLE_RENDER_TYPE_CUSTOM;
var STYLE_RENDER_TYPE_HIDDEN = 'STYLE_RENDER_TYPE_HIDDEN'; // 可编辑的div标签

exports.STYLE_RENDER_TYPE_HIDDEN = STYLE_RENDER_TYPE_HIDDEN;
var STYLE_RENDER_TYPE_CONTENT_EDIT_DIV = 'STYLE_RENDER_TYPE_CONTENT_EDIT_DIV'; // 可展开面板

exports.STYLE_RENDER_TYPE_CONTENT_EDIT_DIV = STYLE_RENDER_TYPE_CONTENT_EDIT_DIV;
var STYLE_RENDER_TYPE_COLLAPSE = 'STYLE_RENDER_TYPE_COLLAPSE'; // 一行两个输入框

exports.STYLE_RENDER_TYPE_COLLAPSE = STYLE_RENDER_TYPE_COLLAPSE;
var STYLE_RENDER_TYPE_TWO_INPUT = 'STYLE_RENDER_TYPE_TWO_INPUT'; // 图片库

exports.STYLE_RENDER_TYPE_TWO_INPUT = STYLE_RENDER_TYPE_TWO_INPUT;
var STYLE_RENDER_TYPE_PICTURE = 'STYLE_RENDER_TYPE_PICTURE';
/* 属性值类型 */
// 数字型

exports.STYLE_RENDER_TYPE_PICTURE = STYLE_RENDER_TYPE_PICTURE;
var STYLE_VALUE_TYPE_NUMBER = 'STYLE_VALUE_TYPE_NUMBER'; // 多个属性值设置使用key

exports.STYLE_VALUE_TYPE_NUMBER = STYLE_VALUE_TYPE_NUMBER;
var STYLE_KEY_TYPE_ALL = 'STYLE_KEY_TYPE_ALL';
/** 预览动画的类型 */
// 预览整个动画

exports.STYLE_KEY_TYPE_ALL = STYLE_KEY_TYPE_ALL;
var TYPE_PREVIEW_ANIMATE_ALL = 'TYPE_PREVIEW_ANIMATE_ALL'; // 预览其中一个动画

exports.TYPE_PREVIEW_ANIMATE_ALL = TYPE_PREVIEW_ANIMATE_ALL;
var TYPE_PREVIEW_ANIMATE_CURRENT = 'TYPE_PREVIEW_ANIMATE_CURRENT'; // 预览鼠标悬浮某个动画

exports.TYPE_PREVIEW_ANIMATE_CURRENT = TYPE_PREVIEW_ANIMATE_CURRENT;
var TYPE_PREVIEW_ANIMATE_HOVER = 'TYPE_PREVIEW_ANIMATE_HOVER';
exports.TYPE_PREVIEW_ANIMATE_HOVER = TYPE_PREVIEW_ANIMATE_HOVER;