export function getArtShadowOptions() {
  return [
    {
      textShadowX: 0,
      textShadowY: 0,
      textShadowSpread: 4,
      textShadowColor: '#6b7d99',
    },
    {
      textShadowX: 0,
      textShadowY: 0,
      textShadowSpread: 4,
      textShadowColor: '#a158b3',
    },
    {
      textShadowX: 0,
      textShadowY: 0,
      textShadowSpread: 4,
      textShadowColor: '#000000',
    },
    {
      textShadowX: 0,
      textShadowY: 0,
      textShadowSpread: 4,
      textShadowColor: '#c4433c',
    },
    {
      textShadowX: 0,
      textShadowY: 0,
      textShadowSpread: 4,
      textShadowColor: '#e05404',
    },
    {
      textShadowX: 0,
      textShadowY: 0,
      textShadowSpread: 4,
      textShadowColor: '#194588',
    },
  ];
}

export function getArtSolidOptions() {
  return [
    {
      textShadowX: 3,
      textShadowY: 4,
      textShadowSpread: 2,
      textShadowColor: '#9faec7',
      textSolidSize: 3,
      textSolidColor: '#d78a35',
      textSolidAngle: 135,
      fontWeight: 'bold',
      color: '#f7e3b9',
    },
    {
      textShadowX: 3,
      textShadowY: 4,
      textShadowSpread: 2,
      textShadowColor: '#9fbeec',
      textSolidSize: 3,
      textSolidColor: '#3d68a8',
      textSolidAngle: 164,
      fontWeight: 'bold',
      color: '#83aae2',
    },
    {
      textShadowX: 3,
      textShadowY: 4,
      textShadowSpread: 2,
      textShadowColor: '#ffffff',
      textSolidSize: 4,
      textSolidColor: '#e77494',
      textSolidAngle: 172,
      fontWeight: 'bold',
      color: '#ecb63d',
    },
    {
      textShadowX: 3,
      textShadowY: 4,
      textShadowSpread: 2,
      textShadowColor: '#ffffff',
      textSolidSize: 3,
      textSolidColor: '#000000',
      textSolidAngle: 155,
      fontWeight: 'bold',
      color: '#7171ef',
    },
    {
      textShadowX: 3,
      textShadowY: 4,
      textShadowSpread: 2,
      textShadowColor: '#9faec7',
      textSolidSize: 3,
      textSolidColor: '#ff79a2',
      textSolidAngle: 135,
      fontWeight: 'bold',
      color: '#6f97da',
    },
    {
      textShadowX: 3,
      textShadowY: 4,
      textShadowSpread: 2,
      textShadowColor: '#9faec7',
      textSolidSize: 3,
      textSolidColor: '#fb8535',
      textSolidAngle: 187,
      fontWeight: 'bold',
      color: '#fdc245',
    },
  ];
}
